const houses = [
  {
    id: 1,
    title: "Modern Beach House",
    description: "Stunning beachfront property with panoramic ocean views.",
    beds: 4,
    bathrooms: 3,
    rate: 350,
    discount: 10,
    area: 4300,
    location: "Hyderabad",
    added: "June 18, 2022",
    latitude: 17.3850,
    longitude: 78.4867
  },
  {
    id: 2,
    title: "Cozy Mountain Cabin",
    description: "Charming cabin nestled in the woods with a fireplace and hot tub.",
    beds: 2,
    bathrooms: 1,
    rate: 200,
    discount: 15,
    area: 4300,
    location: "Hyderabad",
    added: "June 18, 2022",
    latitude: 17.3905,
    longitude: 78.4983
  },
  {
    id: 3,
    title: "Luxury City Penthouse",
    description: "Sleek and spacious penthouse apartment in the heart of the city.",
    beds: 3,
    bathrooms: 2,
    rate: 500,
    discount: 0,
    area: 4300,
    location: "Hyderabad",
    added: "June 18, 2022",
    latitude: 17.3959,
    longitude: 78.4784
  },
  {
    id: 4,
    title: "Rustic Farmhouse Retreat",
    description: "Quaint farmhouse surrounded by fields and rolling hills.",
    beds: 3,
    bathrooms: 2,
    rate: 250,
    discount: 20,
    area: 4300,
    location: "Bangalore",
    added: "June 18, 2022",
    latitude: 12.9716,
    longitude: 77.5946
  },
  
  {
    id: 5,
    title: "Urban Loft with Skyline View",
    description: "Industrial-style loft apartment with floor-to-ceiling windows offering stunning city views.",
    beds: 2,
    bathrooms: 2,
    rate: 400,
    discount: 10,
    area: 4300,
    location: "Bangalore",
    added: "June 18, 2022",
    latitude: 12.9715,
    longitude: 77.5938
  },
  {
    id: 6,
    title: "Secluded Forest Retreat",
    description: "Hideaway cabin surrounded by lush forest, ideal for nature lovers.",
    beds: 1,
    bathrooms: 1,
    rate: 180,
    discount: 8,
    area: 4300,
    location: "Mumbai",
    added: "June 18, 2022",
    latitude: 19.0760,
    longitude: 72.8777
  },
  {
    id: 7,
    title: "Historic Townhouse",
    description: "Elegant townhouse with period features and a charming courtyard garden.",
    beds: 4,
    bathrooms: 3,
    rate: 300,
    discount: 12,
    area: 4300,
    location: "Mumbai",
    added: "June 18, 2022",
    latitude: 19.0759,
    longitude: 72.8775
  },
  {
    id: 8,
    title: "Mountain View Chalet",
    description: "Chic chalet with stunning mountain views and ski-in/ski-out access.",
    beds: 3,
    bathrooms: 2,
    rate: 280,
    discount: 15,
    area: 4300,
    location: "Mumbai",
    added: "June 18, 2022",
    latitude: 19.0762,
    longitude: 72.8780
  },
  {
    id: 9,
    title: "Beachfront Bungalow",
    description: "Quaint bungalow steps away from the sandy shores, perfect for a relaxing getaway.",
    beds: 2,
    bathrooms: 1,
    rate: 220,
    discount: 10,
    area: 4300,
    location: "Chennai",
    added: "June 18, 2022",
    latitude: 13.0827,
    longitude: 80.2707
  },
  {
    id: 10,
    title: "Eco-Friendly Treehouse Retreat",
    description: "Sustainable treehouse nestled in the canopy, surrounded by nature and wildlife.",
    beds: 1,
    bathrooms: 1,
    rate: 120,
    discount: 10,
    area: 4300,
    location: "Chennai",
    added: "June 18, 2022",
    latitude: 13.0828,
    longitude: 80.2710
  },
  {
    id: 11,
    title: "Contemporary Lakeside Villa",
    description: "Sleek and modern villa overlooking a tranquil lake, with private dock and swimming pool.",
    beds: 5,
    bathrooms: 4,
    rate: 600,
    discount: 0,
    area: 4300,
    location: "Chennai",
    added: "June 18, 2022",
    latitude: 13.0826,
    longitude: 80.2705
  },
  {
    id: 12,
    title: "Lakefront Cottage",
    description: "Cozy cottage overlooking a peaceful lake, perfect for fishing and relaxation.",
    beds: 1,
    bathrooms: 1,
    rate: 150,
    discount: 5,
    area: 4300,
    location: "Bangalore",
    added: "June 18, 2022",
    latitude: 12.9717,
    longitude: 77.5950
  }
];

export default houses;
